[package]
name = "rob_lightning"
version.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
bevy = {workspace = true}
